Fix get_ip failed when doesn't install ifconfig
hugegraph/hugegraph-tools pull request #13
Opened 2018-11-20 11:35 UTC by Linary

Fix #12

Change-Id: I2ae4e4e6e3d1749981155e477887a8a4269a26ba

2018-11-22 09:39 UTC, zhoney requested changes

2018-11-22 09:39 UTC, zhoney commented on assembly/bin/util.sh
> +        echo "command $cmd is available"
if exist, no need to echo info

2018-11-22 09:39 UTC, zhoney commented on assembly/bin/util.sh
> +            if [[ `command_available ifconfig` ]]; then
"ifconfig"

2018-11-22 09:39 UTC, zhoney commented on assembly/bin/util.sh
> +                ip=`ifconfig  | grep -E 'inet.[0-9]' | grep -v "$loopback" | awk '{ print $2}'`
two space after "ifconfig"

2018-11-22 09:39 UTC, zhoney commented on assembly/bin/util.sh
> +                echo "Required ifconfig or ip but they are not installed"
use "unavailable" instead of "not installed"

2018-11-22 12:54 UTC, zhoney requested changes

2018-11-22 12:54 UTC, zhoney commented on assembly/bin/util.sh
> +                echo "Required ifconfig or ip but they are available"
unavailable

2018-11-22 12:54 UTC, zhoney commented on assembly/bin/util.sh
> +                echo "Required ifconfig but it is available"
ditto

2018-11-22 12:54 UTC, zhoney commented on assembly/bin/util.sh
> +                echo "Required ifconfig but it is available"
ditto

2018-11-22 13:00 UTC, zhoney submitted a review, later dismissed

2018-11-22 13:23 UTC, javeme requested changes

2018-11-22 13:23 UTC, javeme commented on assembly/bin/util.sh
> +                exit 1
prefer to set: ip=$loopback;;

2018-11-22 13:33 UTC, javeme approved these changes

2018-11-23 03:06 UTC, zhoney approved these changes

2018-11-23 03:07 UTC, merged