Compatible with hugegraph 0.8 when restore graph data
hugegraph/hugegraph-tools pull request #34
Opened 2019-04-23 09:21 UTC by zhoney

Also:
1. add backup/restore progress
2. backup/restore default type is 'all'

implemented: #33

Change-Id: I78ceea26179e7eed6a5661b971f4ac92bc7b89ac

2019-04-23 10:02 UTC, javeme requested changes

2019-04-23 10:02 UTC, javeme commented on src/main/java/com/baidu/hugegraph/base/LocalDirectory.java
> +            is = new FileInputStream(path);
return here

2019-04-23 10:02 UTC, javeme commented on src/main/java/com/baidu/hugegraph/base/LocalDirectory.java
> +        } catch (IOException | IllegalStateException e) {
remove IllegalStateException

2019-04-23 10:02 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/BackupManager.java
> +        System.out.print("Vertices has been backup: 0\b");
Printer. printInBackward(string)

2019-04-24 02:33 UTC, javeme requested changes

2019-04-24 02:33 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        public List<HugeType> types = HugeTypeListConverter.ALL_TYPES;
update description
and improve default value of '-d'

2019-04-24 11:02 UTC, javeme requested changes

2019-04-24 11:02 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        public String logDir = "./backup-log";
./logs

2019-04-24 11:02 UTC, javeme commented on src/main/java/com/baidu/hugegraph/base/Printer.java
> +        printInBackward(0);
0L

2019-04-24 11:02 UTC, javeme commented on src/main/java/com/baidu/hugegraph/base/HdfsDirectory.java
> +                        "'fs.default.name' can not be null or empty " +
use HDFS_FS_DEFAULT_NAME instead

2019-04-24 12:54 UTC, javeme submitted a review, later dismissed

2019-04-25 03:55 UTC, javeme requested changes

2019-04-25 03:55 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/BackupManager.java
> +            for (int startIndex = 0; startIndex < length; startIndex += BATCH) {
startIndex => start
endIndex => end

2019-04-25 03:55 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/BackupManager.java
> +            for (int startIndex = 0; startIndex < length; startIndex += BATCH) {
why not move this loop to backup()

2019-04-25 06:01 UTC, javeme approved these changes

2019-04-25 06:10 UTC, Linary approved these changes

2019-04-25 06:12 UTC, merged