clear log4j warn by using log4j2
hugegraph/hugegraph-tools pull request #39
Opened 2019-05-06 09:52 UTC by zhoney

resolved: #38

Change-Id: Ia46c1921aa0fbbf463c5ccf1b50f7f1d304a599f

2019-05-06 10:07 UTC, javeme requested changes

2019-05-06 10:07 UTC, javeme commented on src/main/resources/log4j2.xml
> +</configuration>
add new line

2019-05-06 10:09 UTC, javeme approved these changes

2019-05-07 00:09 UTC, Linary approved these changes

2019-05-07 00:09 UTC, merged