support migrate subcommand
hugegraph/hugegraph-tools pull request #45
Opened 2019-10-24 09:16 UTC by zhoney

implemented: #35

Change-Id: Ib5493f4dc7d6b606f8e64e390df43103d51aa458

2019-10-24 11:30 UTC, javeme requested changes

2019-10-24 11:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +    private static SubCommands.Backup migrate2Backup(
convMigrate2Backup

2019-10-24 11:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +    private static SubCommands.Restore migrate2Restore(
ditto

2019-10-24 11:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/base/HdfsDirectory.java
> +                         "Directory '%s' not exists", this.directory());
"The directory does not exist: '%s'"

2019-10-24 11:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/base/LocalDirectory.java
> +                     "Directory '%s' not exists", dir.getAbsolutePath());
ditto

2019-10-31 06:03 UTC, Linary submitted a review, later dismissed

2019-11-04 03:56 UTC, javeme requested changes

2019-11-04 03:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        @Parameter(names = {"--remove"},
prefer --clean

2019-11-04 03:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                   description = "Whether to remove graph schema/data")
Whether to remove the directory of graph data after restored

2019-11-04 03:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                   description = "Whether to remove graph schema/data")
ditto

2019-11-04 05:09 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/RestoreManager.java
> +    private boolean remove;
clean

2019-11-04 05:13 UTC, javeme approved these changes

2019-11-04 05:16 UTC, Linary approved these changes

2019-11-04 05:16 UTC, merged