Add client https method
hugegraph/hugegraph-tools pull request #58
Opened 2020-06-21 05:10 UTC by shzcore

2020-06-22 01:54 UTC, zhoney requested changes

2020-06-22 01:54 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                   description = "The Protocol of HugeGraph-Server,allowed values" +
add “blank” after ","

2020-06-22 01:54 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        @Parameter(names = {"--trustStoreFile"}, arity = 1,
--trust-store-file

2020-06-22 01:54 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        @Parameter(names = {"--trustStorePassword"}, arity = 1,
--trust-store-password

2020-06-22 01:54 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                description = "The password of the path of the client truststore " +
align with "names"

2020-06-22 01:54 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                        "Invalid --protocol '%s', valid value is %s",
align with "ParameterException"

2020-06-22 01:54 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +    public void TrustStorePassword(String TrustStorePassword) {
TrustStorePassword -> trustStorePassword

2020-06-22 01:54 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +    private SubCommands.TrustStoreFile trustStoreFile = new SubCommands.TrustStoreFile();
wrap to keep not exceed 80 chars every line

2020-06-22 01:54 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +    private SubCommands.TrustStorePassword trustStorePassword = new SubCommands.TrustStorePassword();
ditto

2020-06-22 01:54 UTC, zhoney commented on assembly/bin/hugegraph
> +    echo "Warning: please set JAVA_HOME variable, otherwise the use of"
Warning seems not completed. Please improve

2020-06-28 04:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +    private SubCommands.TrustStoreFile trustStoreFile = new SubCommands.
wrap line after "=" and align "new" with "trustStoreFile"

2020-06-28 04:24 UTC, javeme commented on assembly/bin/hugegraph
> +    echo "Warning: please set JAVA_HOME variable, otherwise it will affect https related use"
otherwise some libraries related to https may be missing

2020-07-07 08:33 UTC, zhoney requested changes

2020-07-07 08:33 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        private static final Set<String> SSL_PROTOCOL = ImmutableSet.of(
prefer rename `SSL_PROTOCOL` to `PROTOCOLS`

2020-07-07 09:36 UTC, zhoney approved these changes

2020-07-20 06:53 UTC, javeme approved these changes

2020-07-20 06:58 UTC, merged