improve exception info for failed to construct managers
hugegraph/hugegraph-tools pull request #67
Opened 2020-10-27 09:37 UTC by zhoney

Change-Id: Ib6cd0d4d961a8556cee71498dbc0fcd67fc9e43c

2020-10-27 13:08 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                      "--timeout=%s", clz, this.url(), this.graph(),
clz.getSimpleName()

2020-10-27 13:08 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/DumpGraphManager.java
> +        this.directory = this.directory(dump.directory(), dump.hdfsConf());
assign in this.directory()

2020-10-27 13:08 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/DumpGraphManager.java
> +                        "Split size must >= 1M, but got %s", splitSize);
move to splitSize()

2020-10-28 03:49 UTC, Linary submitted a review, later dismissed

2020-10-28 05:20 UTC, javeme requested changes

2020-10-28 05:20 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/BackupRestoreBaseManager.java
> +        this.directory = HdfsDirectory.constructDir(dir, this.graph(),
add else block

2020-10-28 07:06 UTC, javeme approved these changes

2020-10-28 09:21 UTC, houzhizhen approved these changes

2020-10-28 09:41 UTC, merged