remove --protocol args
hugegraph/hugegraph-tools pull request #72
Opened 2020-11-16 10:23 UTC by zhoney

Change-Id: I48772554458ba4e9ac8ffc4e418a433b8a0aab20

2020-11-16 12:11 UTC, javeme requested changes

2020-11-16 12:11 UTC, javeme commented on src/main/java/com/baidu/hugegraph/base/ToolClient.java
> +                              String username, String password, Integer timeout,
wrap line after "String password,"

2020-11-16 12:11 UTC, javeme commented on src/main/java/com/baidu/hugegraph/base/ToolClient.java
> +                                .configSSL(info.trustStoreFile,
set trustStoreFile to default value if info.url starts with 'https' and trustStoreFile is empty

2020-11-17 09:33 UTC, Linary approved these changes, later dismissed

2020-11-17 10:32 UTC, javeme requested changes

2020-11-17 10:32 UTC, javeme commented on src/main/java/com/baidu/hugegraph/base/ToolClient.java
> +    private static final String DEFAULT_TRUST_STORE_PASSWORD = "123456";
set hugegraph

2020-11-17 10:32 UTC, javeme commented on src/main/java/com/baidu/hugegraph/base/ToolClient.java
> +    private static final String DEFAULT_TRUST_STORE_FILE = "./bin/keystore";
move to conf

2020-11-18 12:33 UTC, Linary approved these changes

2020-11-18 12:35 UTC, javeme approved these changes

2020-11-18 12:35 UTC, merged