add auth backup and auth restore
hugegraph/hugegraph-tools pull request #76
Opened 2020-11-30 02:16 UTC by xuliguov5

2020-11-30 03:30 UTC, javeme requested changes

2020-11-30 03:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                            "Invalid --type '%s', valid value is 'all' or " +
align with  ParameterException

2020-11-30 03:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                    "Strategy can't be null or empty");
align

2020-11-30 03:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                        "Invalid --strategy '%s', valid value is 'stop' or 'ignore", value));
align with ParameterException, and ensure don't exceed 80 chars

2020-11-30 03:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupManager.java
> +                          "Bad backup type: %s", type));
align with AssertionError

2020-11-30 03:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupManager.java
> +                                "querying users of authority");
align with this

2020-11-30 03:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupManager.java
> +                                  "querying groups of authority");
also check other places for alignment

2020-11-30 03:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +    /**
use "/*" here,  "/**" is just for java doc

2020-11-30 03:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +
remove empty lines

2020-11-30 03:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +    public static void main(String[] strings) {
remove unused code

2020-12-02 07:56 UTC, javeme requested changes

2020-12-02 07:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                Printer.print("Auth backup start !");
"Auth backup start..."

2020-12-02 07:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                Printer.print("Auth restore start !");
ditto

2020-12-02 07:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        System.exit(0);
throw exception if test mode else System.exit(-1)

2020-12-02 07:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +
remove empty line

2020-12-02 07:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                   description = "restore strategy, " +
improve description

2020-12-02 07:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +            implements IStringConverter<List<HugeType>> {
align with class

2020-12-02 07:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/constant/AuthRestoreFlow.java
> +    ;
move to previous line

2020-12-02 07:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/constant/AuthRestoreStrategy.java
> + */
update licence

2020-12-02 07:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupManager.java
> +            switch (type) {
is there type ALL

2020-12-02 07:56 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthTest.java
> +
remove unused line

2020-12-02 07:56 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/ClientUtil.java
> +
ditto

2020-12-02 07:56 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/FileUtil.java
> +
ditto

2020-12-02 07:56 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/FileUtil.java
> +                    is.close();
use `try (resource)` to auto close

2020-12-02 07:56 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/FileUtil.java
> +                }catch (Exception e) {
add space tp "}catch"

2020-12-02 09:14 UTC, zhoney requested changes

2020-12-02 09:14 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +import com.beust.jcommander.*;
don't use * in import

2020-12-02 09:14 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +import java.util.*;
put java.* and org.* first and put com.baidu.hugegraph last

2020-12-02 09:14 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/constant/AuthRestoreFlow.java
> +/*
add apache license

2020-12-02 09:14 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +
delete empty line

2020-12-03 03:24 UTC, zhoney requested changes

2020-12-03 03:24 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/base/ToolClient.java
> +
delete empty line

2020-12-03 03:24 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/base/ToolClient.java
> +import java.nio.file.Paths;
format imports

2020-12-03 04:24 UTC, javeme requested changes

2020-12-03 04:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        JCommander jCommander = parseJCommand(args, cmd);
rename to parseCommand and catch it

2020-12-03 04:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +            printCommonCommand(jCommander);
printCommandsCategory

2020-12-03 04:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                      "\ncommands, such as './bin/hugegraph help'");
help
help sub-command

2020-12-03 04:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +             }
only print if type y else not, default is [n]

2020-12-03 04:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        System.out.println("Input yes or no to view the stack " +
Type y(yes) to print exception stack[default n]?

2020-12-03 04:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +import com.baidu.hugegraph.manager.*;
don't import *

2020-12-03 04:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +    }
use jcommand instead

2020-12-03 04:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                      "make sure your command, you can use " +
Unexpected command

2020-12-03 04:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                          "Exception in 'main' is", e);
Failed to execute command

2020-12-07 10:23 UTC, zhoney requested changes

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 " .’all' means all vertices, edges and schema,in " +
add a blank after ","

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +
add
```
public int retry(int retry) {
```

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 "event of a conflict in restore. strategy include " +
Valid Strategies

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +
delete empty line

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupManager.java
> +/*
add apache license

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupManager.java
> +                              "Bad backup type: %s", type));
Bad auth backup type

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupManager.java
> +                                     e, type, type.string());
e, list, type.string()

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupManager.java
> +
delete empty line

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +
delete one empty line

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +                    hdfsConf);
align with “dir”

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +                                     e, type, type.string());
ditto

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +        if (!StringUtils.isEmpty(strategy)) {
check strategy not null or empty

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/BackupRestoreBaseManager.java
> +import com.baidu.hugegraph.base.*;
don't import *

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/BackupRestoreBaseManager.java
> +             String line;
I think keep origin is ok

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +    public static void shutdown(List<ToolManager> taskManager) {
taskManagers

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +                      "Failed to parse command");
```
            throw new ParameterException("Failed to parse command");
```

2020-12-07 10:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +                      "Failed to parse command");
ditto

2020-12-07 13:23 UTC, zhoney requested changes

2020-12-07 13:23 UTC, zhoney commented on assembly/travis/conf/gremlin-server.yaml
> +          com.baidu.hugegraph.util.DateUtil
update after https://github.com/hugegraph/hugegraph/pull/1289 merge

2020-12-07 13:23 UTC, zhoney commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +public class AuthRestoreTest extends AuthTest{
add blank before "{"

2020-12-07 13:23 UTC, zhoney commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +        Assert.assertTrue(targetMap.containsKey("test_target1"));
belong and access?

2020-12-07 13:23 UTC, zhoney commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +    public void testAuthRestoreByStrategyConfict() {
Conflict

2020-12-07 13:23 UTC, zhoney commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +        });
also assert exception message

2020-12-07 13:23 UTC, zhoney commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +        });
ditto

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +                                            boolean isTestNode) {
testMode

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +        Printer.print("Can use 'hugegraph help' or " +
Can use 'hugegraph help' to get detail help info of all sub-commands or 
'hugegraph help sub-command' to get detail help info of one sub-command

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +    public static boolean isPrintStackException() {
public static boolean printExceptionStackByUserChoise(Throwable e)

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        String helpValue = Strings.EMPTY;
subCommand

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        if (list.contains(Constants.COMMAND_HELP) &&
```
if (list.contains(Constants.COMMAND_HELP)) {
    int index = list.indexOf(Constants.COMMAND_HELP);
    if (list.size() > index + 1) {
        subCommand = list.get(index + 1);
    }
}
```

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        if (StringUtils.isNotEmpty(helpValue)) {
```
if (StringUtils.isEmpty(helpValue)) {
    return;
}
if (commanderMap.containsKey(helpValue)) {
```

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +        Map<String, User> userMap = Maps.newHashMap();
move to line 156

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +            if (userMap.containsKey(restoreUser.name())) {
```
if (userMap.containsKey(restoreUser.name())) {
    continue
```

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +                                    "Restore users strategy is not fund");
found

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +        for (String str : belongJsons) {
belong

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +                User resourceUser = userMap.get(restoreUser.name());
existUser

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +            if (checkIdMaps(restoreBelong.user().toString(),
improve checkIdMaps

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +        Printer.print("Restore accesses finished, counts is %s !", counts);
count

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +                       }, "Restore targets of authority");
belongs

2020-12-07 13:23 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +    private boolean checkIdMaps(String oneId, String otherId) {
checkAllExist

2020-12-09 08:23 UTC, javeme requested changes

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        this.parseCommand(args);
prefer to let parseCommand  return jCommander

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        String subCommand = this.jCommander.getParsedCommand();
rename to this.jCommander.subCommand()

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        Map<String, JCommander> commanderMap = this.jCommander.getCommands();
use commands() instead of getCommands(), the code style suggests removing useless 'get'

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                              cmd.taskManagers);
move to previos line

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                   description = "That Strategy that needs to be chosen in the " +
The strategy needs to be chosen

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 "’stop’ and ‘ignore’, default is ’stop’. ’stop’ means " +
replace `’` to `'`

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                   description = "Type of auth " +
improv "Type of auth"

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 "Concat with ',' if more than one. " +
missing punctuation before "Concat"

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/constant/AuthRestoreStrategy.java
> +    public static AuthRestoreStrategy getEnumByName(String name) {
fromName

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/BackupRestoreBaseManager.java
> +import static com.baidu.hugegraph.base.Directory.closeAndIgnoreException;
call it through Directory.closeAndIgnoreException()

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +    public static RuntimeException targetRuntimeException(Throwable t) {
what the target means

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +            ToolUtil.shutdown(cmd == null ?
move shutdown method to HugeGraphCommand class

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +    private List<ToolManager> taskManagers = Lists.newArrayList();
assign taskManagers  in constructor

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +    public void parseCommandForHelp(String[] args) {
seems no one call this method

2020-12-09 08:23 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +            cmd = new HugeGraphCommand();
move out of try-catch

2020-12-09 08:23 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +            Assert.assertTrue(msg.endsWith("The following option is required: [--init-password]"));
seems exceed 80 chars

2020-12-09 08:23 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +        this.loadData("./auth-backup/" + HugeType.USER.string(),
refactor loadData() to just pass params HugeType.USER and "auth_users_conflict.txt"

2020-12-09 08:23 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/FileUtil.java
> +public class FileUtil {
move to test.util

2020-12-09 08:25 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +            ToolUtil.exitOrThrow(Constants.EXIT_CODE_ERROR, this.testMode());
only call exit in main()

2020-12-10 04:36 UTC, javeme requested changes

2020-12-10 04:36 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +            Assert.assertContains("java.lang.IllegalArgumentException: Restore " +
Assert.assertThrows(IllegalArgumentException.class

2020-12-10 04:36 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +                                  "users conflict with stop strategy", msg);
update to STOP strategy to avoid ambiguity

2020-12-10 04:36 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +        this.loadData(HugeType.USER.string(), "/auth/auth_users.txt");
passing HugeType.USER enum is ok

2020-12-10 04:36 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +                                  "contains 'group' and 'target'.", msg);
"if type contains 'access' then 'group' and 'target' are required

2020-12-10 04:36 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/util/ClientUtil.java
> +    public HugeClient hugeClient;
don't set public as possible

2020-12-10 04:36 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +        this.loadData(HugeType.USER.string(), "/auth/auth_users.txt");
also remove "/auth/" prefix

2020-12-10 04:36 UTC, javeme commented on src/main/java/com/baidu/hugegraph/exception/ExitException.java
> +        super(message);
prefer use tow params like reason and details, reason is for error overview

2020-12-10 04:36 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                this.taskManagers.add(tasksManager);
try to call this.taskManagers.add() in manager() method

2020-12-10 04:36 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +            ToolUtil.printCommandsCategory(jCommander);
don't print here

2020-12-10 04:36 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +                        this.checkUseConflict();
checkUserConflict

2020-12-10 04:36 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +    public void doAuthRestore(List<HugeType> types, int status) {
pass status as AuthRestoreFlow.CHECK

2020-12-10 04:36 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +                        this.restoreUsers();
does not need to restore if no check?

2020-12-10 04:36 UTC, javeme commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +    public static void printExceptionStackByUserChoise(Throwable e) {
printExceptionStackIfNeeded

2020-12-10 04:36 UTC, javeme commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +                      "\nof all sub-commands or 'hugegraph help sub-command' " +
remove "\n" and adjust by the console

2020-12-10 04:36 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/util/FileUtil.java
> +                       e, filePath);
align with "Failed read

2020-12-10 04:36 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +                                     return this.client.authManager().createGroup(restoreGroup);
align

2020-12-10 04:36 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +                                       return this.client.authManager().createTarget(restoreTarget);
align

2020-12-10 04:36 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                              "combination of 'user,group,target," +
"combination of [user,group,target,...]"

2020-12-10 14:24 UTC, javeme requested changes

2020-12-10 14:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +                        this.checkUseConflict();
address it: it's checkUser not checkUse

2020-12-10 14:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +                          return this.client.authManager().createAccess(restoreAccess);
add 8 spaces is ok

2020-12-10 14:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +        sb.append("Can use 'hugegraph help' to get detail help info " +
Please use 'hugegraph help'

2020-12-10 14:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +                  "of all sub-commands or 'hugegraph help sub-command' " +
hugegraph help {sub-command}

2020-12-10 14:24 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +            Assert.assertContains("Restore users conflict with STOP strategy", msg);
we can use "e.getMessage()" and wrap line

2020-12-10 14:24 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +        FileUtil.writeText(DEFAULT_URL + hugeType.string(), list);
define var for:
DEFAULT_TEST_URL + dataFilePath
DEFAULT_URL + hugeType.string()

2020-12-10 14:24 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/util/ClientUtil.java
> +    protected HugeClient hugeClient;
set private since added public method

2020-12-10 14:24 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/util/ClientUtil.java
> +    public HugeClient hugeClient() {
client()

2020-12-10 14:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                      "Print help command usage detail and exit");
improve reason message and show it for users

2020-12-11 04:39 UTC, javeme requested changes

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +    public static void exitWithUsageOrThrow(ExitException e,
exitOrThrow

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +            sb.append("||");
"|"

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +    public static String commandsCategoryDetails(JCommander jCommander) {
commandsCategory

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +    public static void printException(Throwable e,
printOrThrow

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +                                      boolean testMode) {
throwMode

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        }
call exit if error != 0

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +            throw new ParameterException(String.format(
IllegalArgumentException, or ExitException(-1, ...)

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                      "Unexpected help sub-command %s", subCommand));
sub-command '%s'

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        Map<String, JCommander> commanderMap = jCommander.getCommands();
prefer commands

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        jCommander.parse(args);
```
if (!this.parseHelp()) {
  jCommander.parse(args);
}
```

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +    public void parseCommandForHelp(String[] args, JCommander jCommander) {
parseHelp

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                      "Command is null, print help command usage detail and exit");
throw IllegalArgument

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                      "Print help sub-command usage detail and exit");
hugegraph help {sub-command}

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        public String convert(String value) {
return AuthRestoreStrategy

2020-12-11 04:39 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                throw new ParameterException(String.format(
move to E.checkArgument

2020-12-14 07:19 UTC, javeme requested changes

2020-12-14 07:19 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        if(exitCode == Constants.EXIT_CODE_ERROR) {
exitCode != 0

2020-12-14 07:19 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        if(exitCode == Constants.EXIT_CODE_ERROR) {
add space after "if"

2020-12-14 07:19 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                                    String.format("Hugegragh help %s", subCommand));
make ExitException accept args

2020-12-14 07:19 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        //parse command for throw mode
add space "//" and use uppercase "Parse"

2020-12-14 07:19 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        //parse command for throw mode
"for throw mode" seems not proper

2020-12-14 07:19 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/CommandTest.java
> +        }, (e) -> {
"(e)" => "e"

2020-12-14 07:19 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/CommandTest.java
> +    public void helpCommandTest() {
uniform template testXX

2020-12-14 07:19 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/util/ClientUtil.java
> +    protected void hugeClient() {
rename to newClient

2020-12-14 07:19 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/util/ClientUtil.java
> +    public HugeClient client() {
prefer to delete ClientUtil class since there is no more features than HugeClient

2020-12-14 07:22 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 "than one. other types include ‘all’ and ‘schema’" +
improve chinese "‘"

2020-12-14 07:27 UTC, javeme requested changes

2020-12-14 07:27 UTC, javeme commented on src/main/java/com/baidu/hugegraph/exception/ExitException.java
> +    }
also add normal()

2020-12-14 07:27 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +    private void loadData(HugeType hugeType, String dataFilePath) {
move to end of class

2020-12-14 07:27 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +    public void testAuthRestoreByUser() {
testAuthRestoreForUsers

2020-12-14 07:27 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +    public void testAuthRestoreWithException() {
with what exception

2020-12-14 07:27 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +    public void testAuthRestoreByStrategyIgnore() {
testAuthRestoreWithStrategyIgnore

2020-12-14 07:57 UTC, zhoney requested changes

2020-12-14 07:57 UTC, zhoney commented on assembly/travis/conf/gremlin-server.yaml
> +          com.baidu.hugegraph.util.DateUtil
merged, rebase

2020-12-14 07:57 UTC, zhoney commented on assembly/travis/conf/hugegraph.properties
> +gremlin.graph=com.baidu.hugegraph.auth.HugeFactoryAuthProxy
updated in https://github.com/hugegraph/hugegraph/pull/1293

2020-12-16 06:54 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +        //Parse the '--throw-mode' command
"// Parse"

2020-12-16 06:54 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                                       "No sub-Command found");
sub-command

2020-12-16 06:54 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                                       "Hugegragh help %s", subCommand);
hugegragh

2020-12-16 06:54 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 " .'all' means all vertices, edges and schema, in " +
move space to the back of "."

2020-12-17 06:12 UTC, javeme requested changes

2020-12-17 06:12 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 " 'all' means all vertices, edges and " + "schema, in " +
remove " + "

2020-12-17 06:12 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +    private class AuthUser extends AuthRestore{
UserManager extends AuthManager

2020-12-17 06:12 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +public class AuthRestoreManager extends BackupRestoreBaseManager {
rename to AuthBackupRestoreManager

2020-12-17 06:12 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthRestoreManager.java
> +    private abstract class AuthRestore {
use interface and also add backup() method

2020-12-17 09:24 UTC, javeme requested changes

2020-12-17 09:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                    new UserManager().backup();
keep the same process with restore

2020-12-17 09:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +        if (CollectionUtils.isNotEmpty(this.authManagers)) {
remove the if-statement

2020-12-17 09:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +    private static final int conflict_status = 0;
use uppercase and rename to NO_CONFLICT

2020-12-17 09:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +    private static final String AUTH_RESTORE_DIR = "auth-restore";
seems AUTH_BACKUP_NAME and AUTH_RESTORE_DIR should be the same directory

2020-12-17 09:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/util/ToolUtil.java
> +                                      boolean testMode) {
address it: testMode
and align with Throwable

2020-12-17 09:24 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +    public void testAuthRestoreByTypesWithBelongException() {
testAuthRestoreByBelongWithoutDependency

2020-12-17 09:24 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/CommandTest.java
> +            Assert.assertContains("Command : hugegragh help",
assert details

2020-12-18 08:07 UTC, javeme requested changes

2020-12-18 08:07 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/CommandTest.java
> +            ExitException exception = (ExitException)e;
add space before e: "(ExitException)e"

2020-12-18 08:07 UTC, javeme commented on src/main/java/com/baidu/hugegraph/constant/AuthRestoreFlow.java
> +public enum AuthRestoreFlow {
unused class?

2020-12-18 08:07 UTC, javeme commented on src/main/java/com/baidu/hugegraph/constant/AuthRestoreStrategy.java
> +public enum AuthRestoreStrategy {
AuthRestoreConflictStrategy

2020-12-18 08:07 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +    private void doAddAuths(List<HugeType> types) {
addAuthManagers

2020-12-18 08:07 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                    this.authManagers.add(new UserManager());
change authManagers to local var

2020-12-18 08:07 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +    private List<String> read(HugeType type) {
readXx

2020-12-18 08:07 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +    private long writeText(HugeType type, List<?> list) {
writeXx

2020-12-18 08:07 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +               collect(Collectors.toList());
align with "."
```
hugeTypes.stream()
         .sorted()
         .collect()
```

2020-12-18 08:07 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                      "The following option is required: [--init-password]"));
call E.checkArgument()

2020-12-18 08:07 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                                    "Restore users conflict with STOP strategy, " +
just add this user to conflict list

2020-12-18 08:07 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +            authManager.checkConflict();
collect all the conflicts and print error message if exist any one:
"Conflicts encountered before restoring users and stop this action"

2020-12-18 08:07 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                        }, "Restore belongs of authority");
align with retry(

2020-12-18 08:07 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthBackupTest.java
> +    public void testAuthBackupWithTypesException() {
replace all the 'Exception' to specific exception

2020-12-18 08:07 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/util/FileUtil.java
> +    public static List<String> getFileDirectoryNames(String filePath) {
subdirectories

2020-12-18 08:07 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/util/FileUtil.java
> +    public static long writeText(String filePath, List<?> list) {
repeated method?

2020-12-18 14:17 UTC, javeme requested changes

2020-12-18 14:17 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +            E.checkArgument(AuthRestoreConflictStrategy.STOP.string().equals(value) ||
exceed 80 chars, we can add AuthRestoreConflictStrategy.STOP.match(value) method

2020-12-18 14:17 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                                 }, "Restore users of authority");
align with User

2020-12-18 14:17 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                                   }, "Restore groups of authority");
ditto

2020-12-18 14:17 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                    E.checkArgument(strategy != AuthRestoreConflictStrategy.STOP,
don't check it since will return conflicts if strategy=STOP

2020-12-18 14:17 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                                     }, "Restore targets of authority");
ditto

2020-12-18 14:17 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/util/FileUtil.java
> +    public static List<String> getFileSubdirectories(String filePath) {
just subdirectories() method is ok

2020-12-18 14:17 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                                      restoreTarget.name()));
use conflicts.add(restoreTarget) and rewrite restoreTarget.toString

2020-12-18 14:17 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +    private List<String> conflicts;
just let checkConflict() return `List<String> conflicts`

2020-12-18 14:30 UTC, javeme requested changes

2020-12-18 14:30 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +        Assert.assertThrows(IllegalArgumentException.class, () -> {
don't throw IllegalArgumentException, prefer IllegalStateException

2020-12-18 14:30 UTC, javeme commented on src/test/java/com/baidu/hugegraph/test/functional/AuthRestoreTest.java
> +    public void testAuthRestoreWithStopStrategy() {
testAuthRestoreWithConflictAndStopStrategy

2020-12-18 14:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                    throw new ParameterException(String.format(
replace ParameterException with IllegalArgumentException

2020-12-18 14:30 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +            authManager.checkConflict();
address it

2020-12-18 14:35 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        public void retry(int retry) {
move to line 849

2020-12-18 14:35 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        public String convert(String value) {
address it

2020-12-18 14:41 UTC, javeme requested changes

2020-12-18 14:41 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        public void retry(int retry) {
move to line 849, put similar methods together

2020-12-18 14:41 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        public String convert(String value) {
address it

2020-12-23 12:47 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                            " 'stop' or 'ignore", value);
put space to the previous line

2020-12-23 12:47 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                return client.authManager().createUser(restoreUser);
add 4 spaces

2020-12-23 12:47 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                return client.authManager().createTarget(restoreTarget);
ditto

2020-12-23 12:47 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                 belongMap.put(belong.user() + ":" + belong.group(),
add local var `key = belong.user() + ":" + belong.group()`

2020-12-23 12:47 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                     }, "Restore belongs of authority");
align with retry

2020-12-23 12:47 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                     }, "Restore access of authority");
ditto

2020-12-25 11:45 UTC, javeme requested changes

2020-12-25 11:45 UTC, javeme commented on src/main/java/com/baidu/hugegraph/constant/AuthRestoreConflictStrategy.java
> +    public static boolean matchStrategy(AuthRestoreConflictStrategy strategy) {
seems unused method

2020-12-25 11:45 UTC, javeme commented on src/main/java/com/baidu/hugegraph/constant/AuthRestoreConflictStrategy.java
> +    public static boolean matchStopStrategy(AuthRestoreConflictStrategy strategy) {
don't set static and change to isStopStrategy(), move to line 53
also add isIgnoreStrategy()

2020-12-25 11:45 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 "'user', must init user password.")
please specify the init-password of users

2020-12-25 11:45 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 "of a conflict in restore. valid strategies include " +
in restore => when restoring

2020-12-25 12:49 UTC, javeme commented on checkstyle.xml
> +</module>
add empty line

2020-12-25 13:36 UTC, javeme requested changes

2020-12-25 13:36 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +            Printer.print("Restore groups finished, count is %d !", count);
"..., total count is %d"

2021-01-04 03:56 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                                         "querying belongs of authority");
initial capitalization?

2021-01-04 05:00 UTC, javeme submitted a review, later dismissed

2021-01-04 12:06 UTC, zhoney requested changes

2021-01-04 12:06 UTC, zhoney commented on src/test/java/com/baidu/hugegraph/test/util/FileUtil.java
> +        List<String> resultList = Lists.newArrayList();
resultList => results

2021-01-04 12:06 UTC, zhoney commented on src/test/java/com/baidu/hugegraph/test/util/FileUtil.java
> +             throw new ToolsException("Failed writeText file path is %s",
Failed write file path is

2021-01-04 12:06 UTC, zhoney commented on src/test/java/com/baidu/hugegraph/test/util/FileUtil.java
> +    public static void clearFile(String filePath) {
seems function is clear directories

2021-01-04 12:06 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 "of a conflict when restoring. valid " +
Valid

2021-01-04 12:06 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 " in other words, 'all' equals with 'user, group, target, " +
. In other words

2021-01-04 12:06 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 "belong, access'. in addition, only 'belong' or 'access' " +
In addition

2021-01-04 12:06 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                                 "can not backup or restore, if type contains 'belong' " +
'belong' or 'access' can not backup or restore alone

2021-01-04 12:06 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        private AuthTypes types = new AuthTypes();
move types to AuthBackupRestore

2021-01-04 12:06 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                                     e, resultList, type.string());
type.string(), resultList

2021-01-04 12:06 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                                       "querying users of authority");
groups

2021-01-04 12:06 UTC, zhoney commented on src/main/java/com/baidu/hugegraph/manager/AuthBackupRestoreManager.java
> +                }, "restore access of authority");
accesses

2021-01-05 04:00 UTC, javeme approved these changes, later dismissed

2021-01-05 06:31 UTC, javeme approved these changes

2021-01-05 06:56 UTC, zhoney approved these changes

2021-01-05 08:10 UTC, merged