Support restore in restoring mode and merging mode
hugegraph/hugegraph-tools pull request #9
Opened 2018-10-15 13:19 UTC by zhoney

Change-Id: Ie8dcf37cbef696d4acd5b9faf32d703fb8a3f5c4

2018-11-21 07:20 UTC, javeme requested changes

2018-11-21 07:20 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +        private static final Set<String> RESTORE_MODES = ImmutableSet.of(
defined in client

2018-11-21 07:20 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/RestoreManager.java
> +    private static Map<String, Long> primaryKeyVLs = null;
don't set static due to not shared by multi graphs

2018-11-21 11:13 UTC, javeme requested changes

2018-11-21 11:13 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/HugeGraphCommand.java
> +                            this.subCommand("graph-mode-get");
align with graphModeGet

2018-11-21 11:13 UTC, javeme commented on src/main/java/com/baidu/hugegraph/cmd/SubCommands.java
> +                   description = "Graph mode, [NONE, RESTORING, MERGING]",
"Graph mode, include: [NONE, RESTORING, MERGING]

2018-11-21 11:13 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/RestoreManager.java
> +    private void processVertexIdInEdge(List<Edge> edges) {
updateVertexIdInEdge

2018-11-21 11:13 UTC, javeme commented on src/main/java/com/baidu/hugegraph/manager/RestoreManager.java
> +                processVertexIdInEdge(subEdges);
rename to updateVertexIdInEdge
and comment why needed

2018-11-22 05:10 UTC, javeme approved these changes

2018-11-22 05:38 UTC, Linary approved these changes

2018-11-22 05:38 UTC, merged